Repository team-GIFT/gift, pull requests merged in 2022-01, with the labels that each got.

#11 Add usecase Resolves #10
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/usecase.drawio
  docs/usecase.png
Labels: documentation

#20 config: Create Initial Setting Files
  .eslintignore
  .eslintrc.json
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  babel.config.js
  package-lock.json
  package.json
  public/index.html
  src/App/App.stories.tsx
  src/App/App.styled.tsx
  src/App/App.tsx
  src/App/App.type.ts
  src/assets/logo.svg
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/Card/Template.html
  src/components/index.ts
  src/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/types/custom.d.ts
  tsconfig.json
  webpack/config.build.js
  webpack/config.dev.js
  webpack/config.server.js
Labels: config

#21 config: Modify Configuration Files
  .gitignore
  package-lock.json
  package.json
  public/index.html
Labels: config

#24 config: Fix eslint & prettier env crash - Fix #23
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
Labels: bug, config

#28 Implement Temporary GiphyAPI
  babel.config.js
  package-lock.json
  package.json
  src/api/fetchData.ts
  src/api/index.ts
  src/types/custom.d.ts
  webpack/config.dev.js
Labels: enhancement

#30 Create Card Component
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/Card/Template.html
  src/components/Card/assets/icon_favorite.svg
  src/components/Card/assets/icon_link.svg
Labels: enhancement, style, component, storybook

#36 feat: Create global style component - Close #17
  .eslintrc.json
  package-lock.json
  package.json
  src/index.tsx
  src/styles/global.styled.ts
  src/styles/theme.ts
  src/styles/utils.ts
  tsconfig.json
Labels: style, component

#38 SearchBar, FormInput, A11yHidden component
  package-lock.json
  src/App/App.tsx
  src/components/A11yHidden/A11yHidden.styled.tsx
  src/components/A11yHidden/A11yHidden.tsx
  src/components/A11yHidden/A11yHidden.types.ts
  src/components/FormInput/FormInput.styled.tsx
  src/components/FormInput/FormInput.tsx
  src/components/FormInput/FormInput.types.ts
  src/components/SearchBar/SearchBar.styled.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/SearchBar.type.ts
  src/components/SvgIcon/SvgIcon.type.ts
  src/components/index.ts
Labels: bug, component, config

#44 Develop
  src/components/SvgIcon/SvgIcon.tsx
  src/components/SvgIcon/SvgIcon.type.ts
Labels: fix

#57 feat: Implement Channel Info component - Close #32 #56 #59
  .storybook/preview.js
  package-lock.json
  src/components/ChannelInfo/ChannelInfo.stories.tsx
  src/components/ChannelInfo/ChannelInfo.styled.tsx
  src/components/ChannelInfo/ChannelInfo.tsx
  src/components/ChannelInfo/ChannelInfo.types.ts
  src/styles/theme.ts
Labels: style, component, storybook

#61 Create CardButtonComponent #58 , Create Video Component #55 , Add alt-text that improves accessibility to Card Component #45
  .browserslistrc
  package-lock.json
  package.json
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/Card/assets/icon_favorite.svg
  src/components/Card/assets/icon_link.svg
  src/components/CardButton/CardButton.stories.tsx
  src/components/CardButton/CardButton.styled.tsx
  src/components/CardButton/CardButton.tsx
  src/components/CardButton/CardButton.types.ts
  src/components/CardButton/assets/clipboard.svg
  src/components/CardButton/assets/favorite.png
  src/components/CardButton/assets/icons.svg
  src/components/CardButton/assets/volume.svg
  src/components/Video/Video.stories.tsx
  src/components/Video/Video.tsx
  src/components/Video/Video.types.ts
  src/components/index.ts
  webpack/config.dev.js
Labels: documentation, enhancement, fix, style, DOM, component, storybook, types

#62 Create Loco component and temparary main for release
  package-lock.json
  package.json
  src/App/App.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/Logo.types.ts
  src/components/index.ts
Labels: component

#63 Create Loading Spinner component #39
  .storybook/preview-body.html
  src/components/LoadingSpinner/LoadingSpinner.stories.tsx
  src/components/LoadingSpinner/LoadingSpinner.styled.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/LoadingSpinner/LoadingSpinner.types.ts
  src/styles/global.styled.ts
  src/styles/theme.ts
Labels: enhancement, component

#65 Add title to SvgIcon component
  src/components/SvgIcon/SvgIcon.tsx
Labels: fix

#69 Create Theme Provider
  .storybook/preview.js
  src/components/ChannelInfo/ChannelInfo.styled.tsx
  src/components/LoadingSpinner/LoadingSpinner.styled.tsx
  src/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/index.ts
  src/styles/theme.ts
  src/styles/theme/defaultTheme.d.ts
  src/styles/theme/theme.ts
  src/styles/utils.ts
  src/types/custom.d.ts
Labels: DOM, component

#74 Create Header for width 1040px
  src/App/App.tsx
  src/components/GlobalNav/GlobalNav.stories.tsx
  src/components/GlobalNav/GlobalNav.styled.tsx
  src/components/GlobalNav/GlobalNav.tsx
  src/components/GlobalNav/GlobalNav.types.ts
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/components/Logo/Logo.tsx
  src/components/Logo/Logo.types.ts
  src/components/SearchBar/SearchBar.styled.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SvgIcon/SvgIcon.tsx
  src/components/SvgIcon/SvgIcon.type.ts
  src/components/SvgIcon/assets/user.svg
  src/components/SvgIcon/sprites.svg
  src/components/index.ts
  src/styles/GlobalStyle.tsx
Labels: enhancement, fix, component

#73 Create Tag list component #66
  src/components/TagList/TagList.stories.tsx
  src/components/TagList/TagList.styled.tsx
  src/components/TagList/TagList.tsx
  src/components/TagList/TagList.types.ts
Labels: enhancement, component

#78 Create CarouselComponent #31
  package-lock.json
  package.json
  src/components/Card/Card.styled.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/Carousel.styled.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/Carousel.types.ts
  src/components/Video/Video.tsx
  src/components/index.ts
  src/utils/focusOrTabbable.ts
Labels: DOM, component, storybook

#88 Create Card Container #53, Improve keyboard accessibility in card component #87 , Modify video component #86
  package-lock.json
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/CardButton/CardButton.styled.tsx
  src/components/ChannelInfo/ChannelInfo.tsx
  src/components/Clips/Clips.stories.tsx
  src/components/Clips/Clips.styled.tsx
  src/components/Clips/Clips.tsx
  src/components/Video/Video.tsx
Labels: enhancement, fix, component

#93 Create SubMenu component
  src/components/SubMenu/SubMenu.stories.tsx
  src/components/SubMenu/SubMenu.styled.ts
  src/components/SubMenu/SubMenu.tsx
  src/components/SubMenu/SubMenu.types.ts
Labels: component

#91 Create GirdComp #79 Implement resourse lazy load #75
  package-lock.json
  package.json
  src/components/Card/Card.styled.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/Carousel.types.ts
  src/components/Grid/Grid.stories.tsx
  src/components/Grid/Grid.styled.tsx
  src/components/Grid/Grid.tsx
  src/components/Grid/Grid.types.ts
  src/components/Video/Video.styled.tsx
  src/components/Video/Video.tsx
  src/components/Video/Video.types.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useVideo.ts
  src/utils/getRandom.ts
  src/utils/index.ts
Labels: style, DOM, component, storybook, types

#100 Implement redux global state #96
  package-lock.json
  package.json
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/Carousel/Carousel.tsx
  src/components/Video/Video.types.ts
  src/index.tsx
  src/services/giphy.ts
  src/services/index.ts
  src/store/featrues/giphy/giphy.ts
  src/store/featrues/giphy/giphy.types.ts
  src/store/featrues/index.ts
  src/store/index.ts
Labels: enhancement

#101 Implement Arrow More Link #89
  src/components/ArrowMoreLink/ArrowMoreLink.stories.tsx
  src/components/ArrowMoreLink/ArrowMoreLink.styled.tsx
  src/components/ArrowMoreLink/ArrowMoreLink.tsx
  src/components/ArrowMoreLink/ArrowMoreLink.types.ts
  src/components/SvgIcon/SvgIcon.type.ts
Labels: enhancement, component

#104 Implement Left Side in Detail Page
  src/components/ChannelInfo/ChannelInfo.styled.tsx
  src/components/ChannelInfo/ChannelInfo.tsx
  src/components/ChannelInfo/ChannelInfo.types.ts
  src/components/DetailLeftSide/DetailLeftSide.stories.tsx
  src/components/DetailLeftSide/DetailLeftSide.styled.tsx
  src/components/DetailLeftSide/DetailLeftSide.tsx
  src/components/DetailLeftSide/DetailLeftSide.types.ts
  src/components/DetailLeftSide/assets/instagram@3x.png
  src/components/SvgIcon/SvgIcon.type.ts
  src/components/SvgIcon/assets/new-window.svg
  src/components/SvgIcon/sprites.svg
  src/components/index.ts
  src/services/giphy.ts
Labels: enhancement, component, page

#108 Implement Home Page Comp #102 Provide Store to Stroybook env #107
  .storybook/main.js
  .storybook/preview.js
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/Carousel.types.ts
  src/components/Clips/Clips.styled.tsx
  src/components/Clips/Clips.tsx
  src/components/Grid/Grid.styled.tsx
  src/components/Grid/Grid.tsx
  src/components/Grid/Grid.types.ts
  src/components/Title/Title.types.ts
  src/components/Video/Video.styled.tsx
  src/components/Video/Video.tsx
  src/components/Video/Video.types.ts
  src/pages/Home/Home.stories.tsx
  src/pages/Home/Home.styled.tsx
  src/pages/Home/Home.tsx
  src/pages/index.ts
  src/store/featrues/giphy/giphy.ts
  src/store/featrues/giphy/giphy.types.ts
Labels: storybook, page

#114 Routing and implement Home page
  package-lock.json
  package.json
  src/App/App.tsx
  src/components/Header/Header.styled.tsx
  src/components/SubMenu/SubMenu.styled.ts
  src/components/index.ts
  src/index.tsx
  src/layout/Layout.styled.tsx
  src/layout/Layout.tsx
  src/layout/index.ts
  src/pages/CardDetail/CardDetail.tsx
  src/pages/Home/Home.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/index.ts
  webpack/config.dev.js
Labels: fix, component, config

#119 Implement Wide CardButton, Implement redux types
  src/components/CardButton/CardButton.stories.tsx
  src/components/CardButton/CardButton.styled.tsx
  src/components/CardButton/CardButton.tsx
  src/components/CardButton/CardButton.types.ts
  src/components/Clips/Clips.tsx
  src/components/Grid/Grid.tsx
  src/pages/Home/Home.tsx
  src/services/giphy.ts
  src/services/types/query.ts
  src/store/featrues/giphy/giphy.ts
  src/store/featrues/giphy/giphy.types.ts
  src/store/index.ts
Labels: enhancement, fix

#122 RTK Query Type
  src/services/giphy.ts
  src/services/types/query.ts
Labels: fix

#123 Implement Right Side in Detail page
  src/components/DetailRightSide/DetailRightSide.stories.tsx
  src/components/DetailRightSide/DetailRightSide.styled.tsx
  src/components/DetailRightSide/DetailRightSide.tsx
  src/components/DetailRightSide/DetailRightSide.types.ts
  src/components/TagList/TagList.styled.tsx
  src/components/TagList/TagList.tsx
  src/components/TagList/TagList.types.ts
  src/services/giphy.ts
  src/services/types/query.ts
  src/store/featrues/giphy/giphy.ts
  src/store/featrues/giphy/giphy.types.ts
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: enhancement, fix, component

#124 SearchSuggestions component and networking
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/SearchBar/SearchBar.styled.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/SearchBar.type.ts
  src/components/SearchSuggestions/SearchSuggestions.stories.tsx
  src/components/SearchSuggestions/SearchSuggestions.styled.tsx
  src/components/SearchSuggestions/SearchSuggestions.tsx
  src/components/SearchSuggestions/SearchSuggestions.types.ts
  src/components/index.ts
  src/pages/SearchResult/SearchResult.stories.tsx
  src/pages/SearchResult/SearchResult.styled.tsx
  src/pages/SearchResult/SearchResult.tsx
Labels: enhancement, component

#128 Implement Infinite Scroll #80
  src/components/Carousel/Carousel.tsx
  src/components/Grid/Grid.tsx
  src/components/Grid/Grid.types.ts
  src/components/Video/Video.tsx
  src/hooks/index.ts
  src/hooks/useGrid.ts
  src/hooks/useVideo.ts
  src/pages/Home/Home.tsx
  src/services/giphy.ts
Labels: enhancement, DOM

#129 Responsive Header
  src/components/GlobalNav/GlobalNav.styled.tsx
  src/components/GlobalNav/GlobalNav.tsx
  src/components/GlobalNav/GlobalNav.types.ts
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchSuggestions/SearchSuggestions.styled.tsx
  src/components/SearchSuggestions/SearchSuggestions.tsx
  src/components/SearchSuggestions/SearchSuggestions.types.ts
  src/components/SubMenu/SubMenu.styled.ts
  src/components/SubMenu/SubMenu.tsx
  src/components/SubMenu/SubMenu.types.ts
  src/components/SvgIcon/SvgIcon.type.ts
  src/components/SvgIcon/assets/list.svg
  src/components/SvgIcon/assets/plus.svg
  src/components/SvgIcon/sprites.svg
  src/styles/GlobalStyle.tsx
  src/styles/theme/defaultTheme.d.ts
  src/styles/theme/theme.ts
Labels: enhancement, component

#132 apply cardbutton in detail page, Modify TagList Logic
  src/components/DetailRightSide/DetailRightSide.styled.tsx
  src/components/DetailRightSide/DetailRightSide.tsx
  src/components/TagList/TagList.tsx
  src/components/TagList/TagList.types.ts
  src/components/index.ts
  src/services/giphy.ts
  src/services/types/query.ts
Labels: fix

#137 Make Detail page
  src/components/DetailLeftSide/DetailLeftSide.tsx
  src/components/DetailLeftSide/DetailLeftSide.types.ts
  src/components/DetailRightSide/DetailRightSide.tsx
  src/components/DetailRightSide/DetailRightSide.types.ts
  src/pages/CardDetail/CardDetail.styled.tsx
  src/pages/CardDetail/CardDetail.tsx
  src/services/types/query.ts
Labels: page

#140 SearchResult page : get results from giphy
  src/pages/SearchResult/SearchResult.styled.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/services/giphy.ts
  src/services/types/query.ts
  src/store/featrues/giphy/giphy.ts
  src/store/featrues/giphy/giphy.types.ts
Labels: enhancement, fix, component

#141 Modify Detail page
  src/components/DetailLeftSide/DetailLeftSide.styled.tsx
  src/components/DetailRightSide/DetailRightSide.tsx
  src/components/DetailRightSide/DetailRightSide.types.ts
  src/components/TagList/TagList.tsx
  src/components/TagList/TagList.types.ts
  src/pages/CardDetail/CardDetail.tsx
Labels: fix, page

#144 Search Reulst page finish
  src/components/GlobalNav/GlobalNav.tsx
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/TagList/TagList.tsx
  src/pages/SearchResult/SearchResult.styled.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/store/featrues/giphy/giphy.ts
Labels: fix, page

#145 Apply Skeleton in channel info, Detail gif section and modify card link
  src/components/Card/Card.tsx
  src/components/ChannelInfo/ChannelInfo.styled.tsx
  src/components/ChannelInfo/ChannelInfo.tsx
  src/components/DetailLeftSide/DetailLeftSide.tsx
  src/components/DetailRightSide/DetailRightSide.styled.tsx
  src/components/DetailRightSide/DetailRightSide.tsx
  src/pages/CardDetail/CardDetail.tsx
  src/services/types/query.ts
Labels: fix

#147 Improve web performance #106
  package-lock.json
  package.json
  src/App/App.tsx
  src/components/Card/Card.types.ts
  src/components/Carousel/Carousel.styled.tsx
  src/components/Clips/Clips.styled.tsx
  src/components/Grid/Grid.styled.tsx
  src/components/Video/Video.styled.tsx
  src/components/Video/Video.tsx
  src/pages/Home/Home.styled.tsx
  src/pages/Home/Home.tsx
  src/store/featrues/giphy/giphy.ts
  src/styles/GlobalStyle.tsx
Labels: enhancement

#148 feat: Implement PageNotFound page
  src/components/TagList/TagList.tsx
  src/pages/PageNotFound/PageNotFound.styled.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/services/giphy.ts
Labels: fix, page

#149 fix: Change HTML Anchor Element to React-Router Link
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  webpack/config.dev.js
  webpack/config.server.js
Labels: bug, fix

#151 Fix SearchBar, routing bugs
  src/components/GlobalNav/GlobalNav.styled.tsx
  src/components/GlobalNav/GlobalNav.tsx
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchSuggestions/SearchSuggestions.tsx
  src/components/SearchSuggestions/SearchSuggestions.types.ts
  src/pages/SearchResult/SearchResult.tsx
Labels: bug

#152 Modify build config, routing bugs
  package-lock.json
  package.json
  src/App/App.tsx
  src/assets/favicon.svg
  src/components/ArrowMoreLink/ArrowMoreLink.styled.tsx
  src/components/ArrowMoreLink/ArrowMoreLink.tsx
  src/components/ChannelInfo/ChannelInfo.styled.tsx
  src/components/ChannelInfo/ChannelInfo.tsx
  src/components/DetailLeftSide/DetailLeftSide.tsx
  src/components/DetailRightSide/DetailRightSide.tsx
  src/components/TagList/TagList.styled.tsx
  src/components/TagList/TagList.tsx
  src/index.html
  src/styles/GlobalStyle.tsx
  webpack/config.build.js
Labels: fix, config

#155 Add ChannelInfoComp to CardComp
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/Carousel/Carousel.styled.tsx
  src/components/Carousel/Carousel.tsx
  src/store/featrues/giphy/giphy.ts
Labels: component

#157 Modify build config
  .gitignore
  package-lock.json
  package.json
  public/assets/favicon.svg
  public/index.html
  public/robots.txt
  public/sitemap.xml
  src/pages/CardDetail/CardDetail.tsx
  src/pages/SearchResult/SearchResult.tsx
  webpack/config.build.js
  webpack/config.dev.js
Labels: fix, config
